### PR TITLE
Tasks API example project fixes

### PR DESCRIPTION
**Pull request by sgl0v**
* fixed the project dependencies;
* removed unresolvable/dead outlet refs from the TasksSampleWindow.xib.

### CODE REVIEW

**Comment by thomasvl** [comment]
Sorry not looking sooner, can you squash this into a single commit so we can merge it in as a single fix?

**Comment by sgl0v** [comment]
Squashed into a single commit, as requested above.

**Comment by thomasvl** [comment]
Thanks!

**Comment by thomasvl** [comment]
Oops, that ended up having a blueprint file, we'll likely want to drop that.

**Pull request merged**
