### PR TITLE
Add GTLiOSCore framework

### PR DESCRIPTION
**Pull request by JonasGessner**
This PR adds an embedded framework target for iOS. I've tested it and can confirm that is works fine and as expected.

### CODE REVIEW

**Comment by JonasGessner** [comment]
I signed it!

**Comment by thomasvl** [comment]
What's the second commit, that seems to be something already on trunk?

Looks like you've also got some other project changes (bundle ids), what are those for?

**Comment by JonasGessner** [comment]
In the first commit I also included the recommended changes to the project by Xcode. The second commit was just to rebase my fork. The third fork adds the short version string to the iOS framework Info.plist file, because that is needed when submitting an app to the App Store.

**Comment by thomasvl** [comment]
That second commit that is showing up here (e68ee42) is what has me confused, it should be on trunk already (https://github.com/google/google-api-objectivec-client/commit/baf458dea713acf613dc2b04f8767e94a99464a1).  Do you need to pull/rebase to catch up?

**Comment by thomasvl** [comment]
@gmrobbins fyi - since I believe you are adding the framework also.

**Comment by JonasGessner** [comment]
About the second commit, I forked the repo before you made baf458dea713acf613dc2b04f8767e94a99464a1 so I thought I had to add that to my fork as well, otherwise there would be conflicts in the PR. But I'm probably wrong, I'm not a git master unfortunately...

**Comment by thomasvl** [comment]
I think i got the guts of the framework in commit a50a1be05d05c49661b02215def0788e6fe5216d.

**Pull request closed without merging**
