### PR TITLE
Subspec for the ServiceGenerator project.

### PR DESCRIPTION
**Pull request by eliotstock**
Afraid I don't know how to test this, ie. how to use a local, modified podspec rather than the one on the server.

### CODE REVIEW

**Comment by eliotstock** [comment]
Just signed the CLA.

**Comment by thomasvl** [comment]
You can test things out locally with: `pod spec lint GoogleAPIClient.podspec` and `pod lib lint GoogleAPIClient.podspec`

**Comment by eliotstock** [comment]
The spec lint fails for me. I don't understand the error.

pod spec lint GoogleAPIClient.podspec

 -> GoogleAPIClient

 -> GoogleAPIClient (1.0.2)
    - NOTE  | [GoogleAPIClient/Core] xcodebuild:  warning: hash mismatch: this object file was built against a different version of the module /var/folders/dn/mqg_0vcj2zbfn7sp136z17gw0000gn/C/org.llvm.clang.Eliot/ModuleCache/887W9QZ8N05R/Cocoa-24L2Q5B8ONJG4.pcm
    - ERROR | [GoogleAPIClient/ServiceGenerator] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [GoogleAPIClient/ServiceGenerator] xcodebuild:  GoogleAPIClient/Source/Tools/ServiceGenerator/FHGenerator.h:18:9: fatal error: 'GTLDiscovery.h' file not found
    - NOTE  | [GoogleAPIClient/ServiceGenerator] xcodebuild:  GoogleAPIClient/Source/Tools/ServiceGenerator/FHMain.m:25:9: fatal error: 'GTLDiscovery.h' file not found

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

**Comment by thomasvl** [comment]
The ServiceGenerator probably needs to depend on the Discovery spec and the Core spec so it has the other headers available and they would eventually get linked in.

You may still get errors, but I think it's going to try to pull everything as sdks/frameworks, so the imports have to be <Discovery/GTLDiscovery.h> (or something like that.  It might be easier to add the needed sources directly since you don't really want the generator to depend on the other things as frameworks, etc.

Thinking about this some more, my guess is this will end up trying to amke library/framework out of the generator sources and add that to the things that depends on it.  But you really want to automate making a full OS X binary out of the ServiceGenerator.  That's past my knowledge of cocoapods.  Hopefully someone like @perotinus has some ideas on how to do it/if it is possible.

**Comment by perotinus** [comment]
I don't know of a way to make a subspec that actually produces an app as an output. I think that will require something beyond the subspec, perhaps some additional files/scripts that are downloaded to the Pods directory and can be executed.

**Comment by thomasvl** [comment]
I'm going to close this out since it sounds like this won't work as is, it would take scripting something within a spec for it to work.

**Pull request closed without merging**
